### ISSUE TITLE
jni.h: No such file or directory

### ISSUE THREAD

**Issue by corona10** [timob/jnigi#1]
I found your awsome library to use jni with go lang.
but I got this error message on my Ubuntu 16.04 LTS.

jni.h: No such file or directory

I already install openjdk7 but this error occured... Is there any way to solve this problem?

**Comment by corona10** [comment]
I solved it by setting default-java thanks.

**Comment by timob** [comment]
I've added a new issue for this here: #2 

Glad you like the library. What are you using it for?

**Comment by corona10** [comment]
@timob Thank you for comment. I am looking for a library to using to java library in golang.
But there is no kinds of jpype of python in Golang. :-(
