### ISSUE TITLE
Is it possible to do that for android?

### ISSUE THREAD

**Issue by ajeecai** [timob/jnigi#11]
Hope it can do that for android so that we can write android app  mostly in golang while some can be done in calling java, such as setup service.

Thanks

**Comment by timob** [comment]
Yes.

It should work. I am planning on doing some Android work soon. You could test it with [Android-go](https://github.com/xlab/android-go). Specifically in this [file](https://github.com/xlab/android-go/blob/master/android/jni_util.go). There is a little bit of work to glue these together. You can use [WrapEnv](https://godoc.org/github.com/timob/jnigi#WrapEnv) function to get the java environment from the callback.

I am planning to do a Go binding of the Android SDK soon... If you are keen to work on this, email me at: com@tekao.net

**Comment by ajeecai** [comment]
Thanks for your information, I have written email to you so I close this thread.

**Comment by timob** [comment]
Not sure why you closed this :) Keep working here if you are planning to do any more work on JNIGI Android.

**Comment by jairobjunior** [comment]
Just for future reference... I've been successful using [gomobile](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile) for Android.

**Comment by timob** [comment]
See https://github.com/timob/jnigi/issues/55 for Android support.
