### ISSUE TITLE
concurrent JVMs

### ISSUE THREAD

**Issue by bernardoaraujor** [timob/jnigi#13]
I'm trying to have many JVMs running on concurrent functions (in main()):

```
for i := 0; i < nProcessPass; i++{
		slice = csvSlices[i*sliceSize:(i+1)*sliceSize]
		go processPass(slice, resultChan)
	}
```

where processPass instantiates its own JVM (with a .jar classpath):
```

func processPass(slice [][]string, resultChan chan string){
	//start JVM
	_, env, err := jnigi.CreateJVM(jnigi.NewJVMInitArgs(false, true, jnigi.DEFAULT_VERSION, []string{"-Xcheck:jni", "-Djava.class.path=/home/bernardo/go/src/github.com/bernardoaraujor/corinda/passfault_corinda/out/artifacts/passfault_corinda_jar/passfault_corinda.jar"}))
	if err != nil {
		log.Fatal(err)
	}

	//create TextAnalysis JVM object
	obj, err := env.NewObject("org/owasp/passfault/TextAnalysis")
	if err != nil {
		log.Fatal(err)
	}

	for _, value := range slice{
		fmt.Println(value)

		//create JVM string with password
		str, err := env.NewObject("java/lang/String", []byte(value[2]))

		//call passwordAnalysis on password
		v, err := obj.CallMethod(env, "passwordAnalysis", "java/lang/String", str)
		if err != nil {
			log.Fatal(err)
		}

		//format result from JVM into Go string
		resultJVM, err := v.(*jnigi.ObjectRef).CallMethod(env, "getBytes", jnigi.Byte|jnigi.Array)
		resultGo := string(resultJVM.([]byte))

		fmt.Println(resultGo)
	}
}
```

am I doing something wrong? or jnigi just can't have multiple JVMs running concurrently?

**Comment by timob** [comment]
Hi,

Please see [JNI docs](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#JNI_CreateJavaVM).
`JNI_CreateJavaVM`: "Creation of multiple VMs in a single process is not supported."

JNIGI cannot do things that JNI can't do.

If you are trying to run your method concurrently, maybe you want to use `AttachCurrentThread`.

**Comment by timob** [comment]
Have a look at https://github.com/timob/jnigi/blob/master/jnigi_test.go#L135 `TestAttach` on how to use `AttachCurrentThread`. In your code `processPass` call `AttachCurrentThread` create the object and call the method.

**Comment by bernardoaraujor** [comment]
Cool! I'll dig into it!
Seems kinda obvious, now that you pointed it!

Thanks so much Tim!

Regards,
Bernardo.

On Nov 12, 2017 19:28, "timob" <notifications@github.com> wrote:

Have a look at https://github.com/timob/jnigi/blob/master/jnigi_test.go#L135
TestAttach on how to use AttachCurrentThread. In your code processPass call
AttachCurrentThread create the object and call the method.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/timob/jnigi/issues/13#issuecomment-343769391>, or mute
the thread

**Comment by bernardoaraujor** [comment]
works like a charm! thanks @timob
