### ISSUE TITLE
callMethod is not work for complex function

### ISSUE THREAD

**Issue by fr0zenrain** [timob/jnigi#21]
assume this function:
public com.google.gson.JsonArray test(String input){
}
obj.CallMethod(env, "test", jnigi.ObjectType("com/google/gson/JsonArray"),"java/lang/String", test_str);

but callMethod can not generate the right function signature.it can't distinct test_str is parameter or actual parameter, maybe i incorrectly use of the function.

**Comment by timob** [comment]
The signature is based on the `returnType` and the `args`, you don't need to specify the type for the args. So: 
```
obj.CallMethod(env, "test", jnigi.ObjectType("com/google/gson/JsonArray"), test_str)
```

**Comment by fr0zenrain** [comment]
at last i change the function to return simple String.
your method is ok. thanks.
