### ISSUE TITLE
cgo runtime error No space left on device

### ISSUE THREAD

**Issue by fr0zenrain** [timob/jnigi#28]
sometimes when concurrent execution too much times, cgo will throw a crash ,i use LD_PRELOAD set SA_ONSTACK flag get the reason.
runtime/cgo: pthread_create failed: No space left on device
i think the resource is enough, anyone have encounter this issue, thanks!

**Comment by timob** [comment]
Are you still having this issue?

**Comment by fr0zenrain** [comment]
time is too long and i forgot, may be it has disappered。
