### ISSUE TITLE
Go module version

### ISSUE THREAD

**Issue by dbarganski** [timob/jnigi#37]
Will it be possible to add standard go module version definition? 

Currently these are being resolved as pseudo versions "github.com/timob/jnigi v0.0.0-20200813090134-4fe21c71566a" instead of canonical "vA.B.C" ?

**Comment by timob** [comment]
Sure I'll do a PR soon.

**Comment by timob** [comment]
I will do this I just need to sort out the package name.

**Comment by timob** [comment]
I've added this now. The package name is tekao.net/jnigi.

https://github.com/timob/jnigi/blob/master/go.mod

**Comment by timob** [comment]
This is in master 🎉.
