### ISSUE TITLE
Dockerfile example

### ISSUE THREAD

**Issue by yissatayev** [timob/jnigi#53]
Hi, I am trying to dockerize an application and getting an error on the build stage as follows:

> /go/src/github.com/timob/jnigi/cinit.go:8:9: fatal error: jni.h: No such file or directory
> 8 | #include<jni.h>
> |         ^~~~~~~
> compilation terminated.

My Dockerfile:
```
FROM golang:alpine as BUILD

ENV GO111MODULE=auto

RUN apk update && \
    apk upgrade && \
    apk add git && \
    apk add unzip && \ 
    apk add openssl-dev && \
    apk add build-base && \
    apk add --no-cache gcc musl-dev && \
    apk add --no-cache openjdk8-jre

COPY . /go/src/project
WORKDIR /go/src/project

RUN go get -d -v

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/dist/app

FROM alpine:latest AS FINAL

COPY --from=BUILD /go/dist/app /project-runtime/app

RUN apk update && \
    apk add tzdata && \
    apk add apr && \
    apk add ca-certificates && rm -rf /var/cache/apk/* \
    apk add openssl

RUN update-ca-certificates

WORKDIR /project-runtime

ENTRYPOINT ["./app"]
```

The error happens when the "RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/dist/app" is executed. How should I add the jni.h file? Could you please help me?

**Comment by timob** [comment]
No problem. You need to set `CGO_CFLAGS` to add the include paths for the C headers files.
see https://github.com/timob/jnigi/blob/master/compilevars.sh#L16

**Comment by yissatayev** [comment]
@timob thanks, I was able to resolve the problem.
