### ISSUE TITLE
Why missing uint64 type support?

### ISSUE THREAD

**Issue by GrapeBaBa** [timob/jnigi#57]
We may need pass a Go pointer use uint64 in a method.

**Comment by timob** [comment]
JNI spec for primitive types: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html

So i think we have all those types covered.

**Comment by GrapeBaBa** [comment]
@timob we may need pass uint64 into a java long type, and java call native back to uint64

**Comment by timob** [comment]
Java long is a signed type.

**Comment by GrapeBaBa** [comment]
Got it.
