### ISSUE TITLE
go run example error

### ISSUE THREAD

**Issue by pabcxyz** [timob/jnigi#66]
I get an error when I run the example。
<img width="504" alt="image" src="https://user-images.githubusercontent.com/8225375/191397198-035d04a9-5413-4e1d-a7bb-8af92ba33f81.png">

**Comment by pabcxyz** [comment]
other  error，when I run the example。
<img width="641" alt="image" src="https://user-images.githubusercontent.com/8225375/191489360-2db129b2-ff79-4e55-bc6c-09233de31fee.png">

**Comment by timob** [comment]
Please follow the project readme.
